### ISSUE TITLE
pclean-1.0.0: error in parser

### ISSUE THREAD

**Issue by alunduil** [alunduil/pclean#3]
When running pclean (execution string shown below), we get the following stacktrace:

```
daneel alunduil # pclean -i '' /etc/portage/package.*
Traceback (most recent call last):
  File "/usr/bin/pclean-python3.2", line 9, in <module>
    load_entry_point('pclean==1.0.0', 'console_scripts', 'pclean')()
  File "/usr/lib/python3.2/site-packages/pclean/__init__.py", line 92, in main
    contents = parse(filename)
  File "/usr/lib/python3.2/site-packages/pclean/parsers/__init__.py", line 53, in parse
    return parsers[base](filename)
  File "/usr/lib/python3.2/site-packages/pclean/parsers/general.py", line 38, in general_parser
    cpv, blob = line.strip().split(maxsplit = 1), []
TypeError: split() takes no keyword arguments
```

**Comment by alunduil** [comment]
Closing as this repo is currently abandoned.
