### ISSUE TITLE
pclean-1.0.0: doesn't parse files in a directory structure

### ISSUE THREAD

**Issue by alunduil** [alunduil/pclean#4]
When using the directory layout for `/etc/portage/package.*` the following exception is thrown when parsing one of those individual files:

```
salt-d15630a5-db96-4002-ab68-e68c4fa4ec5e ~ # find /etc/portage/package.* -type f -exec pclean -i '' "{}" +
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/pclean", line 9, in <module>
    load_entry_point('pclean==1.0.0', 'console_scripts', 'pclean')()
  File "/usr/lib64/python3.3/site-packages/pclean/__init__.py", line 92, in main
    contents = parse(filename)
  File "/usr/lib64/python3.3/site-packages/pclean/parsers/__init__.py", line 51, in parse
    logger.info('parser selected: %s', parsers[base])
KeyError: 'pclean'
```

**Comment by alunduil** [comment]
Closing as this repo is currently abandoned.
